version : "3"
services:
  xeb:
    build:
      context: .
      dockerfile: dockerfiles/Web.Dockerfile
    container_name: xeb
    depends_on:
      - xeb-pg
    volumes:
      - .:/var/www/html
    restart: always
    ports:
      - "2000:80"
    environment:
      APP_NAME: "Web boilerplate"
    networks:
      xeb-network:
        ipv4_address: 200.20.1.1
    extra_hosts:
      - host.docker.internal:host-gateway

  xeb-pg:
    image: postgres:15
    container_name: xeb-pg
    volumes:
      - xeb-pg-disk:/var/lib/postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testing
    networks:
      xeb-network:
        ipv4_address: 200.20.1.2

  xeb-q:
    build:
      context: .
      dockerfile: dockerfiles/QueueListener.Dockerfile
    container_name: xeb-q
    depends_on:
      - xeb
    volumes:
      - .:/var/www/html
    restart: unless-stopped
    networks:
      xeb-network:
        ipv4_address: 200.20.1.3

  xeb-mailpit:
    image: 'axllent/mailpit:latest'
    container_name: xeb-mailpit
    restart: always
    networks:
      xeb-network:
        ipv4_address: 200.20.1.4

  xeb-0x:
    build:
      context: .
      dockerfile: dockerfiles/SansXdebug.Dockerfile
    container_name: xeb-0x
    depends_on:
      - xeb
    volumes:
      - .:/var/www/html
    restart: always
    networks:
      xeb-network:
        ipv4_address: 200.20.1.5

  xeb-fe:
    build:
      context: .
      dockerfile: dockerfiles/Fe.Dockerfile
    container_name: xeb-fe
    ports:
      - "2006:5173"
    depends_on:
      - xeb
    volumes:
      - .:/var/www/html
    restart: unless-stopped
    networks:
      xeb-network:
        ipv4_address: 200.20.1.6

# On-disk storage of DB data, when containers are stopped
volumes:
  xeb-pg-disk: {}

# Local network for services running using this docker-compose config
networks:
  xeb-network:
    ipam:
      driver: default
      config:
        - subnet: 200.20.0.0/16
