version : "3"
services:
  web-x:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-x
    depends_on:
      - web-x-pg
    volumes:
      - .:/var/www/html
    restart: always
    ports:
      - "2000:80"
    environment:
      APP_NAME: "Web boilerplate"
    networks:
      web-x-network:
        ipv4_address: 200.20.1.1
    extra_hosts:
      - host.docker.internal:host-gateway

  web-x-pg:
    image: postgres:latest
    container_name: web-x-pg
    volumes:
      - web-x-pg-disk:/var/lib/postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testing
    networks:
      web-x-network:
        ipv4_address: 200.20.1.2

  web-x-q:
    build:
      context: .
      dockerfile: QueueListener.Dockerfile
    container_name: web-x-q
    depends_on:
      - web-x
    volumes:
      - .:/var/www/html
    restart: unless-stopped
    networks:
      web-x-network:
        ipv4_address: 200.20.1.3

  web-x-mailpit:
    image: 'axllent/mailpit:latest'
    container_name: web-x-mailpit
    restart: always
    networks:
      web-x-network:
        ipv4_address: 200.20.1.4

  web-x-vite:
      build:
          context: .
          dockerfile: Vite.Dockerfile
      container_name: web-x-vite
      ports:
        - "2001:5173"
      depends_on:
          - web-x
      volumes:
          - .:/var/www/html
      restart: unless-stopped
      networks:
          web-x-network:
              ipv4_address: 200.20.1.5

# On-disk storage of DB data, when containers are stopped
volumes:
  web-x-pg-disk: {}

# Local network for services running using this docker-compose config
networks:
  web-x-network:
    ipam:
      driver: default
      config:
        - subnet: 200.20.0.0/16
