version : "3"
services:
  watcher-web:
    build:
      context: .
      dockerfile: d-web.Dockerfile
    container_name: watcher-web
    volumes:
      - .:/var/www/html
    restart: "no"
    networks:
      watcher-network:
        ipv4_address: 88.88.8.1

  watcher-pg:
    image: postgres:15
    container_name: watcher-pg
    volumes:
      - watcher-pg-disk:/var/lib/postgres
    restart: "no"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testing
    networks:
      watcher-network:
        ipv4_address: 88.88.8.2

  watcher-mailpit:
    image: 'axllent/mailpit:latest'
    container_name: watcher-mailpit
    restart: "no"
    networks:
      watcher-network:
        ipv4_address: 88.88.8.3

  watcher-vite:
    build:
      context: .
      dockerfile: d-vite.Dockerfile
    container_name: watcher-vite
    volumes:
      - .:/var/www/html
    restart: unless-stopped
    networks:
      watcher-network:
        ipv4_address: 88.88.8.4

# On-disk storage of DB data, when containers are stopped
volumes:
  watcher-pg-disk: {}

# Local network for services running using this docker-compose config
networks:
  watcher-network:
    ipam:
      driver: default
      config:
        - subnet: 88.88.0.0/16

